config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: [:sessions]
  resources :users
  resources :tasks do
    member do
      patch :update_task_status
    end
  end
  root 'tasks#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, optional: true
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable

  has_many :tasks, dependent: :destroy

  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
  validates :role, presence: true
  validate :email, :verify_email_domain

  enum role: { admin: 0, team_mate: 1 }

  scope :except_user, -> (current_user) { where.not(id: current_user.id) }

  before_save :update_username, if: :blank_username

  def verify_email_domain
    if email.present? && %w[gmail.com hotmail.com yahoo.com].include?(email.split('@').last)
      errors.add(:email, 'cannot have the gmail, hotmail, or yahoo domain')
    end
  end

  def update_username
    self.first_name = email.slice(0..1).upcase
  end

  def blank_username
    first_name.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError do
    flash[:danger] = 'You do not have permission to access this page.'
    redirect_to root_url
  end

  rescue_from ActiveRecord::RecordNotFound do
    flash[:notice] = 'Something went Wrong...'
    redirect_to root_url
  end

  rescue_from ActiveRecord::RecordNotDestroyed do
    flash[:notice] = 'Something went Wrong...'
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_task, only: %i[edit update destroy update_task_status]

  def index
    @tasks = Task.all
    authorize @tasks
  end

  def new
    @task = Task.new
    authorize @task
  end

  def create
    @task = Task.new(task_params)
    authorize @task

    if @task.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream
      end
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.turbo_stream
    end
  end

  def update_task_status
    @task.update(is_completed: params[:is_completed])
    redirect_to root_path
  end

  private

    def set_task
      @task = Task.find_by(id: params[:id])
      authorize @task
    end

    def task_params
      params.require(:task).permit(:name, :description, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.except_user(current_user)
    authorize @users
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    @user = User.new(user_params)
    authorize @user

    if @user.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream
      end
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :role).tap { |params| params[:role] = params[:role].to_i }
    end
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <% if type.eql?('notice') %>
    <% classes = 'text-blue-800 border border-blue-300 bg-blue-50' %>
  <% else %>
    <% classes = 'text-red-800 border border-red-300 bg-red-50' %>
  <% end %>

  <div class="absolute z-50 top-0 left-0 right-0 mx-auto w-fit text-center">
    <div class="flex w-fit p-4 mt-5 mb-4 text-sm rounded-lg <%= classes %>" role="alert">
      <svg aria-hidden="true" class="flex-shrink-0 inline w-5 h-5 mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
      <span class="sr-only">Info</span>
      <div>
        <span class="font-medium"><%= type.titleize %>!</span> <%= msg %>
      </div>
    </div>
  </div>
<% end %>
<% flash.clear %>

app/views/layouts/_navbar.html.erb
<nav class="bg-white border-gray-200">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto py-4">
    <a href="/" class="flex items-center">
      <span class="self-center text-2xl font-semibold whitespace-nowrap">Task Management</span>
    </a>
    <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-search">
      <div class="relative mt-3 md:hidden">
        <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
          <svg class="w-5 h-5 text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
        </div>
      </div>
      <ul class="flex flex-col items-baseline p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white">
        <% if user_signed_in? && current_user.admin? %>
          <li>
            <a href="/users" class="block text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0">Users</a>
          </li>
          <li>
          <a href="/tasks" class="block text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0">Tasks</a>
        </li>
        <% elsif user_signed_in? && current_user.team_mate? %>
        <li>
          <a href="/tasks" class="block text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0">Tasks</a>
        </li>
        <% end %>
        <li>
          <% if user_signed_in? %>
            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn-danger' %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path, class: 'btn-primary' %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cards</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='drop-shadow-lg'>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %>
    <main class="container mx-auto mt-16 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task do |form| %>
  <% if task.errors.any? %>
    <% task.errors.full_messages.each do |message|%>
      <% flash[:error] = message %>
      <%= render 'layouts/flash', locals: {flash: flash} %>
    <%end%>
  <%end%>
  <div class='my-6 flex flex-row justify-between gap-4 items-end'>
    <div class='w-1/4'>
      <%= form.label :name, 'Title', class: 'block font-bold mr-5 mb-2 text-sm text-gray-900' %>
      <%= form.text_field :name, class: 'mr-5 input-field', autofocus: true %>
    </div>

    <div class='w-1/4'>
      <%= form.label :user_id, class: 'block font-bold mr-5 mb-2 text-sm text-gray-900' %>
      <%= form.collection_select(:user_id, User.team_mate, :id, :first_name, { prompt: true }, class: 'mr-5 dropdown-select') %>
    </div>

    <div class='w-1/2'>
      <%= form.label :description, class: 'block font-bold mr-5 mb-2 text-sm text-gray-900' %>
      <%= form.text_field :description, class: 'mr-2 input-field', required: true %>
    </div>

    <div class='w-1/6 h-11 flex flex-row justify-end items-end'>
      <%= link_to tasks_path, class: 'btn-danger' do %>
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
      <% end %>
      <%= button_tag class: 'btn-primary' do %>
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg>
      <% end %>
    </div>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<%= turbo_frame_tag task do %>
  <div class='flex flex-row justify-between bg-white border-b hover:bg-gray-50'>
    <div class='w-1/4 py-4 px-6 text-left'>
      <p class='font-normal text-sm text-slate-600 truncate'><%= task.description %></p>
    </div>
    <div class='w-1/5 py-4 px-6 text-left whitespace-nowrap'>
      <p class='font-normal text-sm text-slate-600'><%= task.created_at.strftime("%m/%d/%Y") %></p>
    </div>
    <div class='w-1/5 py-4 px-6 text-left whitespace-nowrap'>
      <p class='font-normal text-sm text-slate-600'><%= task.user.nil? ? 'UnAssigned' : task.user.first_name %></p>
    </div>
    <div class='w-1/5 py-4 px-6 text-left whitespace-nowrap'>
      <p class='font-normal text-sm text-slate-600'><%= task.is_completed ? 'Completed' : 'Incomplete'%></p>
    </div>
    <div class='flex flex-row justify-end w-1/6 py-4 px-6'>
      <% if user_signed_in? && task&.user&.id == current_user.id %>
        <%= button_to 'Complete', update_task_status_task_path(task), method: :patch, params: { is_completed: "#{task.is_completed ? false : true}" }, class: 'btn-success'%>
      <% end %>
      <% if user_signed_in? && current_user.admin?%>
        <%= link_to edit_task_path(task), class: 'btn-success' do %>
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path></svg>
        <% end %>
        <%= button_to task_path(task), method: :delete, class: 'btn-danger' do %>
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.append 'tasks', @task %>
<%= turbo_stream.update Task.new, '' %>

app/views/tasks/destroy.turbo_stream.erb
<%= turbo_stream.remove "task_#{@task.id}" %>

app/views/tasks/edit.html.erb
<%= turbo_frame_tag @task do %>
  <%= render 'form', task: @task %>
<% end %>

app/views/tasks/index.html.erb
<div class='container p-4 rounded-md border'>
  <div class='flex flex-row justify-between mb-10'>
    <h1 class='text-lg font-bold tracking-tight text-blue-dark'> Tasks </h1>
    <% if user_signed_in? && current_user.admin? %>
      <%= link_to new_task_path, class: 'btn-main', data: { turbo_frame: dom_id(Task.new) } do %>
        <div class='flex flex-row items-center pr-2'>
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
          <p>Create Task</p>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= turbo_frame_tag Task.new %>
  <%= turbo_frame_tag 'tasks', class: 'flex flex-col justify-start' do %>
    <div class='flex flex-row justify-between bg-slate-50 border-b hover:bg-gray-50'>
      <div class='w-1/4 py-4 px-6 whitespace-nowrap'>
        <p class='text-left font-medium text-sm text-gray-900'>Description</p>
      </div>
      <div class='w-1/5 py-4 px-6 whitespace-nowrap'>
        <p class='text-left font-medium text-sm text-gray-900'>Created At</p>
      </div>
      <div class='w-1/5 py-4 px-6 whitespace-nowrap'>
        <p class='text-left font-medium text-sm text-gray-900'>Assignee</p>
      </div>
      <div class='w-1/5 py-4 px-6 whitespace-nowrap'>
        <p class='text-left font-medium text-sm text-gray-900'>Task Status</p>
      </div>
      <div class='w-1/6 py-4 px-6'>
      </div>
    </div>
    <%= render @tasks %>
  <% end %>
</div>

app/views/tasks/new.html.erb
<%= turbo_frame_tag @task do %>
  <%= render 'form', task: @task, method: :post, url: tasks_path %>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <% if user.errors.any? %>
    <% user.errors.full_messages.each do |message|%>
      <% flash[:error] = message %>
      <%= render 'layouts/flash', locals: {flash: flash} %>
    <%end%>
  <%end%>
  <div class='mb-6 flex flex-row justify-between gap-4 items-end'>
    <div class='w-1/6'>
      <%= form.label :first_name, class: 'block font-bold mr-5 mb-2 text-sm text-gray-900' %>
      <%= form.text_field :first_name, class: 'mr-5 input-field', autofocus: true %>
    </div>

    <div class='w-1/6'>
      <%= form.label :last_name, class: 'block font-bold mr-5 mb-2 text-sm text-gray-900' %>
      <%= form.text_field :last_name, class: 'mr-5 input-field'%>
    </div>

    <div class='w-1/7'>
      <%= form.label :role, class: 'block font-bold mr-5 mb-2 text-sm text-gray-900' %>
      <%= form.select :role, [['Admin', 0], ['User', 1]], { prompt: true }, class: 'mr-5 dropdown-select' %>
    </div>

    <div class='w-1/5'>
      <%= form.label :email, class: 'block font-bold mr-5 mb-2 text-sm text-gray-900' %>
      <%= form.email_field :email, class: 'mr-5 input-field'%>
    </div>

    <div class='w-1/5'>
      <%= form.label :password, class: 'block font-bold mr-5 mb-2 text-sm text-gray-900' %>
      <%= form.password_field :password, class: 'mr-5 input-field'%>
    </div>

    <div class='w-1/7 h-11 flex flex-row justify-end items-end'>
      <%= link_to users_path, class: 'btn-danger' do %>
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
      <% end %>
      <%= button_tag(class: 'btn-primary') do %>
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<%= turbo_frame_tag user do %>
  <div class='flex flex-row justify-between bg-white border-b hover:bg-gray-50'>
    <div class='w-1/3 py-4 px-6 text-left whitespace-nowrap'>
      <p class='font-normal text-sm text-slate-600'><%= user.first_name + " " + user.last_name %></p>
    </div>
    <div class='w-1/3 py-4 px-6 text-left whitespace-nowrap'>
      <p class='font-normal text-sm text-slate-600'><%= user.email %></p>
    </div>
    <div class='w-1/3 py-4 px-6 text-left whitespace-nowrap'>
      <p class='font-normal text-sm text-slate-600'><%= user.created_at.to_formatted_s(:short) %></p>
    </div>
  </div>
<% end %>

app/views/users/create.turbo_stream.erb
<%= turbo_stream.append 'users', @user %>
<%= turbo_stream.update User.new, '' %>

app/views/users/index.html.erb
<div class='container p-4 rounded-md border'>
  <div class='flex flex-row justify-between mb-10'>
    <h1 class='text-lg font-bold tracking-tight text-blue-dark'> Users </h1>
    <%= link_to new_user_path, class: 'btn-main', data: { turbo_frame: dom_id(User.new) } do %>
      <div class='flex flex-row items-center pr-2'>
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
        <p>Create User</p>
      </div>
    <% end %>
  </div>
  <%= turbo_frame_tag User.new %>
  <%= turbo_frame_tag 'users', class: 'flex flex-col justify-start' do %>
    <div class='flex flex-row justify-between bg-white border-b hover:bg-gray-50'>
      <div class='w-1/3 py-4 px-6 text-left whitespace-nowrap'>
        <p class='font-medium text-sm text-gray-900'>Name</p>
      </div>
      <div class='w-1/3 py-4 px-6 text-left whitespace-nowrap'>
        <p class='font-medium text-sm text-gray-900'>Email</p>
      </div>
      <div class='w-1/3 py-4 px-6 text-left whitespace-nowrap'>
        <p class='font-medium text-sm text-gray-900'>Date Added</p>
      </div>
    </div>
    <%= render @users %>
  <% end %>
</div>

app/views/users/new.html.erb
<%= turbo_frame_tag @user do %>
  <%= render 'form', user: @user, method: :post, url: users_path %>
<% end %>